openapi: 3.0.0
info:
  title: APPESI
  version: 1.0.0
servers:
  - url: 'https://p3-be.ulbi.ac.id'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/sidang/frontend:
    post:
      tags:
        - General
      summary: Post FE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                npm: 353535353
                nama_mhs: Cfvgv gb g
                jsdelivr: 10
                js_module: 10
                kelengkapan_css: 10
                custom_domain: 10
      parameters:
        - name: AUTH
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDI0LTAxLTA0VDEyOjM4OjU0KzA3OjAwIiwiaWF0IjoiMjAyNC0wMS0wNFQxMDozODo1NCswNzowMCIsImlkIjoiNjI4NTE1Njc2ODcxMyIsIm5iZiI6IjIwMjQtMDEtMDRUMTA6Mzg6NTQrMDc6MDAifYRTpMMplJ22l8mdmAO8IEsavsJ__LkZbODKgl7igCsGIfjnmZ4XDVC2ogxxrlvPJ5jM995gMzfUFqjuj1syuQ0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - General
      summary: Edit FE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                npm: 1214017
                namamhs: Data Edit
                jsdelivr: 22
                jsmodule: 22
                kelengkapan_css: 22
                customdomain: 22
      parameters:
        - name: AUTH
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDI0LTAxLTA0VDE3OjUyOjQ3KzA3OjAwIiwiaWF0IjoiMjAyNC0wMS0wNFQxNTo1Mjo0NyswNzowMCIsImlkIjoiNjI4NTE1Njc2ODcxMyIsIm5iZiI6IjIwMjQtMDEtMDRUMTU6NTI6NDcrMDc6MDAifYw7oWpYHN-bT-x5X_L-iAHIxvm9wUb6zjsp5ijRO40z3BWV3gRiu8ZQLGo0gjAvnLxbyb2G7SOkuYG2_Orkpgc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - General
      summary: Get FE All
      security:
        - bearerAuth: []
      parameters:
        - name: token
          in: header
          schema:
            type: string
          example: >-
            v4.public.eyJleHAiOiIyMDIzLTEyLTIyVDE3OjE1OjM1KzA3OjAwIiwiaWF0IjoiMjAyMy0xMi0yMlQxNToxNTozNSswNzowMCIsImlkIjoiNjI4NTE1Njc2ODcxMyIsIm5iZiI6IjIwMjMtMTItMjJUMTU6MTU6MzUrMDc6MDAifUk_3JKtq7hCv1CxFJ5I1xDYD-1UQJGV7pgJX0EQmul2OF8z2PyInSuTHJ8Od3HmSN43eEPj-gC3ylAxv7tUgAI
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/sidang/frontend/get:
    get:
      tags:
        - General
      summary: Get FE By NPM
      parameters:
        - name: npm
          in: query
          schema:
            type: integer
          example: '353535353'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/sidang/backend:
    delete:
      tags:
        - General
      summary: Delete BE By NPM
      parameters:
        - name: npm
          in: query
          schema:
            type: integer
          example: '353535353'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - General
      summary: Post BE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                npm: 353535353
                nama_mhs: Cfvgv gb g
                auth_token: 10
                be_package: 10
                gcf_node: 10
                integrasi_wauth: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - General
      summary: Get BE All
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/sidang/backend/get:
    get:
      tags:
        - General
      summary: Get BE By NPM
      parameters:
        - name: npm
          in: query
          schema:
            type: integer
          example: '353535353'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
